name: Engine Predictor Maintenance Pipeline

on:
  push:
    branches:
      - main  # Automatically triggers on push to the main branch

env:
  MLFLOW_TRACKING_URI: http://127.0.0.1:5000
  ARTIFACT_STORE: ${{ github.workspace }}/mlartifacts

jobs:

  register-dataset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Dependencies
        run: pip install -r predictive_maintenance_project/requirements.txt
      - name: Upload Dataset to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python predictive_maintenance_project/model_building/data_register.py

  data-prep:
    needs: register-dataset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Dependencies
        run: pip install -r predictive_maintenance_project/requirements.txt
      - name: Run Data Preparation
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python predictive_maintenance_project/model_building/preparation.py

  model-training:
    needs: data-prep
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Dependencies
        run: pip install -r predictive_maintenance_project/requirements.txt
      - name: Model Building & Remote Logging
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }} 
        run: |
          cd predictive_maintenance_project/model_building
          python train.py

  deploy-hosting:
    runs-on: ubuntu-latest
    needs: [model-training,data-prep,register-dataset]
    steps:
      - uses: actions/checkout@v5
      - name: Install Dependencies
        run: pip install -r predictive_maintenance_project/requirements.txt
      - name: Push files to Frontend Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python predictive_maintenance_project/hosting/hosting.py
